import type { NewsItem } from '../types/news';
import { hashLink } from './newsCache';

const now = Date.now();
const h = (ms: number) => new Date(now - ms).toISOString();

export const FALLBACK_NEWS: NewsItem[] = [
  {
    id: hashLink('https://www.pcg.gov.ph/patrol-wps-2024'),
    title: 'Philippine Coast Guard Conducts Patrol in West Philippine Sea',
    link: 'https://www.pcg.gov.ph',
    pubDate: h(1 * 3600_000),
    author: 'Philippine Coast Guard',
    thumbnail: '',
    description: 'The Philippine Coast Guard conducted routine maritime patrol operations within the EEZ in the West Philippine Sea.',
    source: 'PCG Official',
    topic: 'wps',
    score: 280,
    priority: 'high',
  },
  {
    id: hashLink('https://www.afp.mil.ph/sierra-madre-resupply'),
    title: 'BRP Sierra Madre Resupply Mission Successfully Completed',
    link: 'https://www.afp.mil.ph',
    pubDate: h(3 * 3600_000),
    author: 'Armed Forces of the Philippines',
    thumbnail: '',
    description: 'Philippine Navy personnel successfully completed a resupply mission to the BRP Sierra Madre stationed at Ayungin Shoal.',
    source: 'AFP',
    topic: 'defense',
    score: 220,
    priority: 'high',
  },
  {
    id: hashLink('https://dfa.gov.ph/sovereign-rights-wps'),
    title: 'Philippines Reaffirms Sovereign Rights Over EEZ Under UNCLOS',
    link: 'https://dfa.gov.ph',
    pubDate: h(6 * 3600_000),
    author: 'Department of Foreign Affairs',
    thumbnail: '',
    description: 'The Philippine government reiterated its sovereign rights and jurisdiction over the EEZ in accordance with UNCLOS and the 2016 Arbitral Award.',
    source: 'DFA Philippines',
    topic: 'diplomacy',
    score: 200,
    priority: 'normal',
  },
  {
    id: hashLink('https://amti.csis.org/scarborough-imagery'),
    title: 'Satellite Imagery Reveals Vessel Activity Near Scarborough Shoal',
    link: 'https://amti.csis.org',
    pubDate: h(12 * 3600_000),
    author: 'AMTI / CSIS',
    thumbnail: '',
    description: 'Recent satellite imagery analyzed by the Asia Maritime Transparency Initiative shows increased vessel activity near Scarborough Shoal.',
    source: 'AMTI CSIS',
    topic: 'maritime',
    score: 260,
    priority: 'high',
  },
  {
    id: hashLink('https://www.pacom.mil/joint-patrol-2024'),
    title: 'US-Philippines Joint Maritime Patrol Reinforces EEZ Presence',
    link: 'https://www.pacom.mil',
    pubDate: h(18 * 3600_000),
    author: 'US Indo-Pacific Command',
    thumbnail: '',
    description: 'US and Philippine naval forces conducted a joint maritime patrol in the South China Sea, reaffirming the alliance and freedom of navigation.',
    source: 'USINDOPACOM',
    topic: 'defense',
    score: 190,
    priority: 'normal',
  },
  {
    id: hashLink('https://dfa.gov.ph/unclos-anniversary'),
    title: 'UNCLOS Arbitral Award Anniversary: Philippines Marks Milestone',
    link: 'https://dfa.gov.ph',
    pubDate: h(24 * 3600_000),
    author: 'DFA Philippines',
    thumbnail: '',
    description: "The Philippines commemorated the anniversary of the landmark UNCLOS Arbitral Award, which invalidated China's expansive claims in the South China Sea.",
    source: 'DFA Philippines',
    topic: 'diplomacy',
    score: 180,
    priority: 'normal',
  },
  {
    id: hashLink('https://www.bfar.da.gov.ph/eez-fishing'),
    title: 'BFAR Monitors Illegal Fishing Vessels Inside Philippine EEZ',
    link: 'https://www.bfar.da.gov.ph',
    pubDate: h(30 * 3600_000),
    author: 'BFAR',
    thumbnail: '',
    description: 'The Bureau of Fisheries and Aquatic Resources reported monitoring of unauthorized foreign fishing vessels operating within the Philippine EEZ.',
    source: 'BFAR',
    topic: 'eez',
    score: 170,
    priority: 'normal',
  },
  {
    id: hashLink('https://www.officialgazette.gov.ph/eez-patrol'),
    title: 'Philippine Navy Deploys Additional Vessels to EEZ Patrol Routes',
    link: 'https://www.officialgazette.gov.ph',
    pubDate: h(36 * 3600_000),
    author: 'Official Gazette',
    thumbnail: '',
    description: 'The Philippine Navy has deployed additional patrol vessels to key EEZ routes to strengthen maritime domain awareness and deter incursions.',
    source: 'Official Gazette',
    topic: 'eez',
    score: 160,
    priority: 'normal',
  },
];
